sudo: required
language: node_js
services:
  - docker

node_js:
  - "4"
install:
  - npm install
script:
  - node ./node_modules/gulp/bin/gulp.js test:development
cache:
  directories:
  - node_modules
after_success:
  - docker login -u worasit501 -p bfmzevdn
  - docker build -t worasit501/nongped-api .
  - docker push worasit501/nongped-api